../../rtl/sopc/ZYNQ_PRV32.v
../../rtl/sopc/rst_sync.v
../../rtl/sopc/irq_sync.v
../../rtl/picorv32/picorv32.v
../../rtl/sopc/amba_ahb_m2s4.v
../../rtl/sopc/apb_slave_mux.v
../../rtl/sopc/ahb_slave_mux.v
../../rtl/sopc/apb_test_slave.v
../../rtl/sopc/ahb_addr_decode.v
../../rtl/sopc/apb_uart.v
../../rtl/sopc/apb_timer.v
../../rtl/sopc/ahb_ram.v
../../rtl/sopc/ahb_pio.v
../../rtl/sopc/ahb_to_apb.v
../../rtl/sopc/apb_subsystem.v
../../rtl/bd/PS7SYS/hdl/PS7SYS.v
../../rtl/bd/PS7SYS/ip/PS7SYS_processing_system7_0_0/hdl/verilog/processing_system7_v5_5_processing_system7.v
../../rtl/bd/PS7SYS/ip/PS7SYS_processing_system7_0_0/synth/PS7SYS_processing_system7_0_0.v

